import fs from 'fs-extra';
import path from 'path';
import ejs from 'ejs';

interface ParsedIntent {
  primaryUser: string;
  secondaryUsers: string[];
  problem: string;
  solution: string;
  vision: string;
  metrics: string[];
  suggestedFeatures: string[];
}

export async function generatePipGovernance(projectName: string, intent: ParsedIntent) {
  const projectPath = path.join(process.cwd(), projectName);
  const pipPath = path.join(projectPath, '.pip');

  // Create directory structure
  await fs.ensureDir(path.join(pipPath, 'mission'));
  await fs.ensureDir(path.join(pipPath, 'method'));
  await fs.ensureDir(path.join(pipPath, 'ia', 'agents'));
  await fs.ensureDir(path.join(pipPath, 'graph'));
  await fs.ensureDir(path.join(pipPath, 'docs'));
  await fs.ensureDir(path.join(pipPath, 'patterns', 'agent-workflows'));

  // Generate mission.md
  const missionTemplate = `# Mission

## Who It Serves
- Primary: <%= primaryUser %>
<% secondaryUsers.forEach(function(user) { %>- Secondary: <%= user %>
<% }); %>

## Problem We Solve
<%= problem %>

## Solution Overview
<%= solution %>

## Vision & Outcomes
- Vision: <%= vision %>
- Outcomes:
<% metrics.slice(0, 3).forEach(function(metric, index) { %>  <%= index + 1 %>. <%= metric %>
<% }); %>

## Success Metrics
<% metrics.forEach(function(metric) { %>- <%= metric %>
<% }); %>

## Non-Goals
- <Explicitly list what we are not doing>

## Current Status
- Lifecycle stage: discovery
- Next milestone: MVP - validate core metrics
`;

  const mission = ejs.render(missionTemplate, intent);
  await fs.writeFile(path.join(pipPath, 'mission', 'mission.md'), mission);

  // Generate initial roadmap
  const roadmapTemplate = `# Product Roadmap

## Suggested Features (from intent analysis)

### P0 - MVP (Must achieve core metric)
<% suggestedFeatures.slice(0, 3).forEach(function(feature) { %>- [ ] <%= feature %>
<% }); %>

### P1 - Enhancements (Improve metric achievement)
<% suggestedFeatures.slice(3, 6).forEach(function(feature) { %>- [ ] <%= feature %>
<% }); %>

### P2 - Nice-to-have
<% suggestedFeatures.slice(6).forEach(function(feature) { %>- [ ] <%= feature %>
<% }); %>

## Feature-to-Metric Mapping

Each feature above should map to at least one success metric:
<% metrics.forEach(function(metric) { %>
### <%= metric %>
- Supported by: [List features that enable this metric]
<% }); %>
`;

  const roadmap = ejs.render(roadmapTemplate, intent);
  await fs.writeFile(path.join(pipPath, 'graph', 'product-app.md'), roadmap);

  // Generate activity log
  const now = new Date().toISOString().split('T')[0];
  const activityLog = `# Activity Log

Log new agent activity for each commit: who did what and why.

| Date (UTC) | Agent | Commit/PR | What changed | Why (rationale) | Links |
| --- | --- | --- | --- | --- | --- |
| ${now} | seed | init | Initialized project with pip governance and hatch foundation | Bootstrap governed project from user intent | mission.md, product-app.md |
`;

  await fs.writeFile(path.join(pipPath, 'docs', 'activity-log.md'), activityLog);

  // Copy remaining pip templates from pip repo (if available)
  // For MVP, we'll create minimal stubs
  await fs.writeFile(
    path.join(pipPath, 'method', 'delivery-method.md'),
    '# Delivery Method\n\nSee pip framework documentation for full methodology.'
  );

  await fs.writeFile(
    path.join(pipPath, 'ia', 'agent_manifest.yml'),
    `agents:
  ceo:
    responsibilities:
      - Approve mission changes
      - Final strategic decisions
  
  cpo:
    responsibilities:
      - Own product roadmap
      - Prioritize features
      - Define success metrics
  
  cto:
    responsibilities:
      - Technical architecture
      - Technology decisions
      - Code quality standards
`
  );

  // Create README for .pip
  const pipReadme = `# Project Governance (.pip)

This directory contains the governance layer for this project, generated by [seed](https://github.com/derrybirkett/seed).

## Structure

- \`mission/\` - Mission statement, vision, success metrics
- \`ia/\` - Information architecture, agent roles
- \`method/\` - Delivery methodology
- \`graph/\` - Product roadmap and feature planning
- \`docs/\` - Activity log, changelog
- \`patterns/\` - Agentic development patterns

## Usage

Refer to mission.md when making product decisions.
Use agent_manifest.yml to understand decision rights.
Update activity-log.md when making significant changes.

For full pip framework documentation, see: https://github.com/derrybirkett/pip
`;

  await fs.writeFile(path.join(pipPath, 'README.md'), pipReadme);
}
